////			 execVM "altisRenovation.sqf";			////
// configuration items
_position = [15360,15360,0];
_range = 21723;

// main
_replaceList = [
	[ "Land_d_Addon_02_V1_F" , "Land_i_Addon_02_V1_F" ],
	[ "Land_d_House_Big_01_V1_F" , "Land_i_House_Big_01_V1_F" ],
	[ "Land_d_House_Big_02_V1_F" , "Land_i_House_Big_01_V1_F" ],
	[ "Land_d_House_Small_01_V1_F" , "Land_i_House_Small_01_V1_F" ],
	[ "Land_d_House_Small_02_V1_F" , "Land_i_House_Small_02_V1_F" ],
	[ "Land_d_Shop_01_V1_F" , "Land_i_Shop_01_V1_F" ],
	[ "Land_d_Shop_02_V1_F" , "Land_i_Shop_02_V1_F" ],
	[ "Land_i_Barracks_V1_dam_F" , "Land_i_Barracks_V1_F" ],
	[ "Land_i_Barracks_V2_dam_F" , "Land_i_Barracks_V2_F" ],
	[ "Land_i_Garage_V1_dam_F" , "Land_i_Garage_V1_F" ],
	[ "Land_i_Garage_V2_dam_F" , "Land_i_Garage_V1_F" ],
	[ "Land_i_Garage_V2_F" , "Land_i_Garage_V1_F" ],
	[ "Land_i_House_Big_01_V1_dam_F" , "Land_i_House_Big_01_V1_F" ],
	[ "Land_i_House_Big_01_V2_dam_F" , "Land_i_House_Big_01_V2_F" ],
	[ "Land_i_House_Big_01_V3_dam_F" , "Land_i_House_Big_01_V3_F" ],
	[ "Land_i_House_Big_02_V1_dam_F" , "Land_i_House_Big_02_V1_F" ],
	[ "Land_i_House_Big_02_V2_dam_F" , "Land_i_House_Big_02_V2_F" ],
	[ "Land_i_House_Big_02_V3_dam_F" , "Land_i_House_Big_02_V3_F" ],
	[ "Land_i_House_Small_01_V1_dam_F" , "Land_i_House_Small_01_V1_F" ],
	[ "Land_i_House_Small_01_V2_dam_F" , "Land_i_House_Small_01_V2_F" ],
	[ "Land_i_House_Small_01_V3_dam_F" , "Land_i_House_Small_01_V3_F" ],
	[ "Land_i_House_Small_02_V1_dam_F" , "Land_i_House_Small_02_V1_F" ],
	[ "Land_i_House_Small_02_V2_dam_F" , "Land_i_House_Small_02_V2_F" ],
	[ "Land_i_House_Small_02_V3_dam_F" , "Land_i_House_Small_02_V3_F" ],
	[ "Land_i_House_Small_03_V1_dam_F" , "Land_i_House_Small_03_V1_F" ],
	[ "Land_i_Shed_Ind_F" , "Land_i_Shed_Ind_F" ],
	[ "Land_i_Shop_01_V1_dam_F" , "Land_i_Shop_01_V1_F" ],
	[ "Land_i_Shop_01_V2_dam_F" , "Land_i_Shop_01_V2_F" ],
	[ "Land_i_Shop_01_V3_dam_F" , "Land_i_Shop_01_V3_F" ],
	[ "Land_i_Shop_02_V1_dam_F" , "Land_i_Shop_02_V1_F" ],
	[ "Land_i_Shop_02_V2_dam_F" , "Land_i_Shop_02_V2_F" ],
	[ "Land_i_Shop_02_V3_dam_F" , "Land_i_Shop_02_V3_F" ],
	[ "Land_u_Addon_01_V1_dam_F" , "Land_i_Addon_02_V1_F" ],
	[ "Land_u_Addon_01_V1_F" , "Land_i_Addon_02_V1_F" ],
	[ "Land_u_Barracks_V2_F" , "Land_i_Barracks_V2_F" ],
	[ "Land_u_House_Big_01_V1_dam_F" , "Land_i_House_Big_01_V1_F" ],
	[ "Land_u_House_Big_01_V1_F" , "Land_i_House_Big_01_V1_F" ],
	[ "Land_u_House_Big_02_V1_dam_F" , "Land_i_House_Big_01_V1_F" ],
	[ "Land_u_House_Big_02_V1_F" , "Land_i_House_Big_01_V1_F" ],
	[ "Land_u_House_Small_01_V1_dam_F" , "Land_i_House_Small_01_V1_F" ],
	[ "Land_u_House_Small_01_V1_F" , "Land_i_House_Small_01_V1_F" ],
	[ "Land_u_House_Small_02_V1_F" , "Land_i_House_Small_02_V1_F" ],
	[ "Land_u_House_Small_02_V1_F" , "Land_i_House_Small_02_V1_F" ],
	[ "Land_u_Shop_01_V1_dam_F" , "Land_i_Shop_01_V1_F" ],
	[ "Land_u_Shop_01_V1_F" , "Land_i_Shop_01_V1_F" ],
	[ "Land_u_Shop_02_V1_dam_F" , "Land_i_Shop_02_V1_F" ],
	[ "Land_u_Shop_02_V1_F" , "Land_i_Shop_02_V1_F" ],
	[ " Land_i_Stone_HouseBig_V1_dam_F" , " Land_i_Stone_HouseBig_V1_F" ],
	[ " Land_i_Stone_HouseBig_V2_dam_F" , " Land_i_Stone_HouseBig_V2_F" ],
	[ " Land_i_Stone_HouseBig_V3_dam_F" , " Land_i_Stone_HouseBig_V3_F" ],
	[ " Land_d_Stone_HouseBig_V1_F" , " Land_i_Stone_HouseBig_V1_F" ],
	[ " Land_i_Stone_Shed_V1_dam_F" , "Land_i_Stone_Shed_V1_F" ],
	[ "Land_i_Stone_Shed_V2_dam_F" , " Land_i_Stone_Shed_V2_F" ],
	[ "Land_i_Stone_Shed_V3_dam_F" , " Land_i_Stone_Shed_V3_F" ],
	[ " Land_d_Stone_Shed_V1_F" , "Land_i_Stone_Shed_V1_F" ],
	[ " Land_i_Stone_HouseSmall_V1_dam_F" , " Land_i_Stone_HouseSmall_V1_F" ],
	[ "Land_i_Stone_HouseSmall_V2_dam_F" , " Land_i_Stone_HouseSmall_V2_F" ],
	[ "Land_i_Stone_HouseSmall_V3_dam_F" , " Land_i_Stone_HouseSmall_V3_F" ],
	[ "Land_d_Stone_HouseSmall_V1_F" , " Land_i_Stone_HouseSmall_V1_F" ],
	[ "Land_Airport_Tower_dam_F" , " Land_Airport_Tower_F" ],
	[ " Land_HighVoltageTower_dam_F" , " Land_HighVoltageTower_F" ],
	[ " Land_spp_Tower_dam_F" , " Land_spp_Tower_F" ],
	[ "Land_TentHangar_V1_dam_F" , "Land_TentHangar_V1_F" ],
	[ "Land_New_WiredFence_10m_Dam_F" , "Land_New_WiredFence_10m_F" ],
	[ " Land_Net_FenceD_8m_F" , " Land_Net_Fence_8m_F" ],
	[ "Land_Stone_8mD_F" , "Land_Stone_8m_F" ],
	[ "Land_WiredFence_01_8m_d_F" , "Land_WiredFence_01_8m_F" ]
	];

{
	_objects = _position nearObjects [_x select 0, _range];
	_replaceWith = _x select 1;

	{
		hideObjectGlobal _x;
		_house = _replaceWith createvehicle getpos _x;
		_house setdir direction _x;
		_house setposASL getposASL _x;
		hintSilent ("Renovating: " + _replaceWith);
	} forEach _objects;

} foreach _replaceList;

_junkList = [
	"Land_Addon_01_ruins_F",
	"Land_Addon_01_V1_ruins_F",
	"Land_Addon_02_ruins_F",
	"Land_Addon_02_V1_ruins_F",
	"Land_Addon_03_ruins_F",
	"Land_Addon_03_V1_ruins_F",
	"Land_Addon_03mid_V1_ruins_F",
	"Land_Addon_04_ruins_F",
	"Land_Addon_04_V1_ruins_F",
	"Land_Addon_05_ruins_F",
	"Land_Airport_Tower_ruins_F",
	"Land_Barracks_ruins_F",
	"Land_BellTower_02_V1_ruins_F",
	"Land_BellTower_02_V2_ruins_F",
	"Land_Boat_01_abandoned_blue_F",
	"Land_Boat_01_abandoned_red_F",
	"Land_Boat_02_abandoned_F",
	"Land_Boat_03_abandoned_F",
	"Land_Boat_04_wreck_F",
	"Land_Boat_05_wreck_F",
	"Land_Boat_06_wreck_F",
	"Land_Bulldozer_01_abandoned_F",
	"Land_Bulldozer_01_wreck_F",
	"Land_cargo_house_slum_ruins_F",
	"Land_Cargo_House_V1_ruins_F",
	"Land_Cargo_House_V2_ruins_F",
	"Land_Cargo_House_V3_ruins_F",
	"Land_Cargo_House_V4_ruins_F",
	"Land_Cargo_HQ_V1_ruins_F",
	"Land_Cargo_HQ_V2_ruins_F",
	"Land_Cargo_HQ_V3_ruins_F",
	"Land_Cargo_HQ_V4_ruins_F",
	"Land_Cargo_Patrol_V1_ruins_F",
	"Land_Cargo_Patrol_V2_ruins_F",
	"Land_Cargo_Patrol_V3_ruins_F",
	"Land_Cargo_Patrol_V4_ruins_F",
	"Land_Cargo_Tower_V1_ruins_F",
	"Land_Cargo_Tower_V2_ruins_F",
	"Land_Cargo_Tower_V3_ruins_F",
	"Land_Cargo_Tower_V4_ruins_F",
	"Land_Cargo20_china_color_V1_ruins_F",
	"Land_Cargo20_china_color_V2_ruins_F",
	"Land_Cargo20_color_V1_ruins_F",
	"Land_Cargo20_color_V2_ruins_F",
	"Land_Cargo20_color_V3_ruins_F",
	"Land_Cargo20_idap_ruins_F",
	"Land_Cargo20_military_ruins_F",
	"Land_Cargo40_china_color_V1_ruins_F",
	"Land_Cargo40_china_color_V2_ruins_F",
	"Land_Cargo40_color_V1_ruins_F",
	"Land_Cargo40_color_V2_ruins_F",
	"Land_Cargo40_color_V3_ruins_F",
	"Land_Cargo40_idap_ruins_F",
	"Land_Cargo40_military_ruins_F",
	"Land_Castle_01_tower_ruins_F",
	"Land_Chapel_Small_V1_ruins_F",
	"Land_Chapel_Small_V2_ruins_F",
	"Land_Chapel_V1_ruins_F",
	"Land_Chapel_V2_ruins_F",
	"Land_Church_01_ruins_F",
	"Land_Church_02_ruins_F",
	"Land_cmp_Hopper_ruins_F",
	"Land_cmp_Shed_ruins_F",
	"Land_cmp_Tower_ruins_F",
	"Land_CombineHarvester_01_wreck_F",
	"Land_dp_bigTank_ruins_F",
	"Land_dp_smallTank_ruins_F",
	"Land_Excavator_01_abandoned_F",
	"Land_Excavator_01_wreck_F",
	"Land_Factory_Conv1_10_ruins_F",
	"Land_Factory_Conv1_Main_ruins_F",
	"Land_Factory_Conv2_ruins_F",
	"Land_Factory_Hopper_ruins_F",
	"Land_Factory_Main_ruins_F",
	"Land_FuelStation_Build_ruins_F",
	"Land_FuelStation_Shed_ruins_F",
	"Land_Garage_V1_ruins_F",
	"Land_GH_Gazebo_ruins_F",
	"Land_GH_House_ruins_F",
	"Land_HaulTruck_01_abandoned_F",
	"Land_HistoricalPlaneDebris_01_F",
	"Land_HistoricalPlaneDebris_02_F",
	"Land_HistoricalPlaneDebris_03_F",
	"Land_HistoricalPlaneDebris_04_F",
	"Land_HistoricalPlaneWreck_01_F",
	"Land_HistoricalPlaneWreck_02_front_F",
	"Land_HistoricalPlaneWreck_02_front_water_F",
	"Land_HistoricalPlaneWreck_02_rear_F",
	"Land_HistoricalPlaneWreck_02_rear_water_F",
	"Land_HistoricalPlaneWreck_02_wing_left_F",
	"Land_HistoricalPlaneWreck_02_wing_right_F",
	"Land_HistoricalPlaneWreck_03_F",
	"Land_House_Big_01_ruins_F",
	"Land_House_Big_01_V1_ruins_F",
	"Land_House_Big_02_V1_ruins_F",
	"Land_House_Native_01_ruins_F",
	"Land_House_Native_02_ruins_F",
	"Land_House_Small_01_ruins_F",
	"Land_House_Small_01_V1_ruins_F",
	"Land_House_Small_02_ruins_F",
	"Land_House_Small_02_V1_ruins_F",
	"Land_House_Small_03_ruins_F",
	"Land_House_Small_03_V1_ruins_F",
	"Land_Kiosk_blueking_ruins_F",
	"Land_LightHouse_ruins_F",
	"Land_Lighthouse_small_ruins_F",
	"Land_Locomotive_01_v1_F",
	"Land_Locomotive_01_v2_F",
	"Land_Locomotive_01_v3_F",
	"Land_Medevac_house_V1_ruins_F",
	"Land_Medevac_HQ_V1_ruins_F",
	"Land_Metal_Shed_ruins_F",
	"Land_MetalShelter_01_ruins_F",
	"Land_MetalShelter_02_ruins_F",
	"Land_MiningShovel_01_abandoned_F",
	"Land_Radar_ruins_F",
	"Land_Radar_Small_ruins_F",
	"Land_RailwayCar_01_passenger_F",
	"Land_RailwayCar_01_sugarcane_empty_F",
	"Land_RailwayCar_01_sugarcane_F",
	"Land_RailwayCar_01_tank_F",
	"Land_Research_house_V1_ruins_F",
	"Land_Research_HQ_ruins_F",
	"Land_ReservoirTank_Airport_ruins_F",
	"Land_ReservoirTank_Rust_ruins_F",
	"Land_ReservoirTank_V1_ruins_F",
	"Land_ReservoirTower_ruins_F",
	"Land_RowBoat_V1_F",
	"Land_RowBoat_V2_F",
	"Land_RowBoat_V3_F",
	"Land_Shed_01_ruins_F",
	"Land_Shed_02_ruins_F",
	"Land_Shed_03_ruins_F",
	"Land_Shed_04_ruins_F",
	"Land_Shed_05_ruins_F",
	"Land_Shed_06_ruins_F",
	"Land_Shed_Big_ruins_F",
	"Land_Shed_Ind_ruins_F",
	"Land_Shed_Small_ruins_F",
	"Land_Shop_01_V1_ruins_F",
	"Land_Shop_02_V1_ruins_F",
	"Land_Shop_Town_01_ruins_F",
	"Land_Shop_Town_02_ruins_F",
	"Land_Shop_Town_03_ruins_F",
	"Land_Shop_Town_04_ruins_F",
	"Land_SlideCastle_ruins_F",
	"Land_Slum_House01_ruins_F",
	"Land_Slum_House02_ruins_F",
	"Land_Slum_House03_ruins_F",
	"Land_spp_Mirror_ruins_F",
	"Land_spp_Tower_ruins_F",
	"Land_spp_Transformer_ruins_F",
	"Land_Stone_HouseBig_V1_ruins_F",
	"Land_Stone_HouseSmall_V1_ruins_F",
	"Land_Stone_Shed_V1_ruins_F",
	"Land_TankWreck_01_turret_F",
	"Land_TBox_ruins_F",
	"Land_Temple_Native_01_ruins_F",
	"Land_TentHangar_V1_ruins_F",
	"Land_TTowerBig_1_ruins_F",
	"Land_TTowerBig_2_ruins_F",
	"Land_Unfinished_Building_01_ruins_F",
	"Land_Unfinished_Building_02_ruins_F",
	"Land_UWreck_FishingBoat_F",
	"Land_UWreck_Heli_Attack_02_F",
	"Land_UWreck_MV22_F",
	"Land_Windmill01_ruins_F",
	"Land_WIP_ruins_F",
	"Land_Wreck_BMP2_F",
	"Land_Wreck_BRDM2_F",
	"Land_Wreck_Car_F",
	"Land_Wreck_Car2_F",
	"Land_Wreck_Car3_F",
	"Land_Wreck_CarDismantled_F",
	"Land_Wreck_Heli_Attack_01_F",
	"Land_Wreck_Heli_Attack_02_F",
	"Land_Wreck_HMMWV_F",
	"Land_Wreck_Hunter_F",
	"Land_Wreck_Offroad_F",
	"Land_Wreck_Offroad2_F",
	"Land_Wreck_Plane_Transport_01_F",
	"Land_Wreck_Skodovka_F",
	"Land_Wreck_Slammer_F",
	"Land_Wreck_Slammer_hull_F",
	"Land_Wreck_Slammer_turret_F",
	"Land_Wreck_T72_hull_F",
	"Land_Wreck_T72_turret_F",
	"Land_Wreck_Traw_F",
	"Land_Wreck_Traw2_F",
	"Land_Wreck_Truck_dropside_F",
	"Land_Wreck_Truck_F",
	"Land_Wreck_UAZ_F",
	"Land_Wreck_Ural_F",
	"Land_Wreck_Van_F",
	"Plane_Fighter_01_wreck_F",
	"Plane_Fighter_02_wreck_F",
	"Plane_Fighter_03_wreck_F",
	"Plane_Fighter_04_wreck_F"
	];


{
	_hide = _x;
	_objects = _position nearObjects [_x, _range];
	{
		hideObjectGlobal _x;
		hintSilent ("Hiding: " + _hide);
	} forEach _objects;

} foreach _junkList;

hint "Altis renovation done.";